name: SonarQube

permissions:
  actions: read
  contents: read

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  sonar-qube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report-enabler
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          path: /github/workspace/enabler/coverage/lcov.info

      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report-processor
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          path: /github/workspace/processor/coverage/lcov.info

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
